[package]
name = "averyark/wip"
version = "0.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["averyark"]
license = "MIT"
description = "Working in progress Framework."

[dependencies]
Janitor = "howmanysmall/janitor@^1.14.2"
BridgeNet = "ffrostflame/bridgenet@2.0.0-rc4"
Signal = "sleitnick/signal@1.0.1"
Promise = "evaera/promise@4.0.0"
t = "osyrisrblx/t@3.0.0"
TableUtil = "tpc9000/tableutil@0.1.1"
ProfileService = "brittonfischer/profileservice@2.1.5"
BoatTween = "penguindevs/boattween@1.0.1"
Astrax = "averyark/astraxv2@0.0.13"
Matter = "evaera/matter@0.6.2"
RaycastHitbox = "ruizukun-dev/raycasthitbox@1.0.2"