[package]
name = "ruizukun-dev/raycasthitbox"
description = "A hit detection system that utilizes Roblox's Raycasting APIs."
version = "1.0.2"
license = "MIT"
authors = ["Swordphin"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

exclude = ["*"]
include = ["lib", "lib/init.lua", "lib/init.meta.json",
"lib/Solvers", "lib/Solvers/Attachment.lua", "lib/Solvers/Bone.lua", 
"lib/Solvers/LinkAttachments.lua", "lib/Solvers/Vector3.lua",
"lib/GoodSignal.lua", "lib/HitboxCaster.lua", "lib/VisualizerCache.lua",    
"default.project.json", "wally.toml"]

[dependencies]
