local ReplicatedStorage = game:GetService("ReplicatedStorage")
return {
    [1] = {
        iconId = "rbxassetid://13006158039",
        id = 1,
        name = "Naruto",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Naruto,
        multiplier = 1.5,
    },
    [2] = {
        iconId = "rbxassetid://13006157783",
        id = 2,
        name = "Itachi",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Itachi,
        multiplier = 1.875,
    },
    [3] = {
        iconId = "rbxassetid://13006157431",
        id = 3,
        name = "Obito",
        rarity = 2,
        model = ReplicatedStorage.items.heros.Obito,
        multiplier = 3,
    },
    [4] = {
        iconId = "rbxassetid://13006157118",
        id = 4,
        name = "Madara",
        rarity = 3,
        model = ReplicatedStorage.items.heros.Madara,
        multiplier = 6,
    },
    [5] = {
        iconId = "rbxassetid://13006156781",
        id = 5,
        name = "Kaguya",
        rarity = 4,
        model = ReplicatedStorage.items.heros.Kaguya,
        multiplier = 10,
    },

    [6] = {
        iconId = "rbxassetid://13338758841",
        id = 6,
        name = "Tanjiro",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Tanjiro,
        multiplier = 12,
    },
    [7] = {
        iconId = "rbxassetid://13338759033",
        id = 7,
        name = "Nezuco",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Nezuco,
        multiplier = 15,
    },
    [8] = {
        iconId = "rbxassetid://13338759169",
        id = 8,
        name = "Zenitsu",
        rarity = 2,
        model = ReplicatedStorage.items.heros.Zenitsu,
        multiplier = 24,
    },
    [9] = {
        iconId = "rbxassetid://13338759319",
        id = 9,
        name = "Kokushibo",
        rarity = 3,
        model = ReplicatedStorage.items.heros["Kokushibo"],
        multiplier = 48,
    },
    [10] = {
        iconId = "rbxassetid://13338759438",
        id = 10,
        name = "Muzan Kibitsuji",
        rarity = 4,
        model = ReplicatedStorage.items.heros["Muzan Kibitsuji"],
        multiplier = 80,
    },

    [11] = {
        iconId = "rbxassetid://13341891261",
        id = 11,
        name = "Levi",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Levi,
        multiplier = 108,
    },
    [12] = {
        iconId = "rbxassetid://13341890625",
        id = 12,
        name = "Mikasa",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Mikasa,
        multiplier = 135,
    },
    [13] = {
        iconId = "rbxassetid://13341890958",
        id = 13,
        name = "Armoured titan",
        rarity = 2,
        model = ReplicatedStorage.items.heros["Armoured titan"],
        multiplier = 216,
    },
    [14] = {
        iconId = "rbxassetid://13341890390",
        id = 14,
        name = "Eren",
        rarity = 3,
        model = ReplicatedStorage.items.heros["Eren"],
        multiplier = 432,
    },
    [15] = {
        iconId = "rbxassetid://13341891528",
        id = 15,
        name = "Zeke",
        rarity = 4,
        model = ReplicatedStorage.items.heros.Zeke,
        multiplier = 720,
    },

    [16] = {
        iconId = "rbxassetid://13342827571",
        id = 16,
        name = "Deku",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Deku,
        multiplier = 907.5,
    },
    [17] = {
        iconId = "rbxassetid://13342826555",
        id = 17,
        name = "Bakugo",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Bakugo,
        multiplier = 1095,
    },
    [18] = {
        iconId = "rbxassetid://13342827247",
        id = 18,
        name = "Todoroki",
        rarity = 2,
        model = ReplicatedStorage.items.heros["Todoroki"],
        multiplier = 1320,
    },
    [19] = {
        iconId = "rbxassetid://13342826880",
        id = 19,
        name = "All M",
        rarity = 3,
        model = ReplicatedStorage.items.heros["All M"],
        multiplier = 1920,
    },
    [20] = {
        iconId = "rbxassetid://13342827942",
        id = 20,
        name = "One For All",
        rarity = 4,
        model = ReplicatedStorage.items.heros["One For All"],
        multiplier = 2720,
    },

    [21] = {
        iconId = "rbxassetid://13342827571",
        id = 21,
        name = "Zoro",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Zoro,
        multiplier = 3470,
    },
    [22] = {
        iconId = "rbxassetid://13342826555",
        id = 22,
        name = "Luffy",
        rarity = 1,
        model = ReplicatedStorage.items.heros.Luffy,
        multiplier = 4220,
    },
    [23] = {
        iconId = "rbxassetid://13342827247",
        id = 23,
        name = "White Beard",
        rarity = 2,
        model = ReplicatedStorage.items.heros["White Beard"],
        multiplier = 5120,
    },
    [24] = {
        iconId = "rbxassetid://13342826880",
        id = 24,
        name = "Kaido",
        rarity = 3,
        model = ReplicatedStorage.items.heros["Kaido"],
        multiplier = 7520,
    },
    [25] = {
        iconId = "rbxassetid://13342827942",
        id = 25,
        name = "Black Beard",
        rarity = 4,
        model = ReplicatedStorage.items.heros["Black Beard"],
        multiplier = 10720,
    }
}