local ReplicatedStorage = game:GetService("ReplicatedStorage")
return {
	["Amenoma Kageuchi"] = {
		name = "Amenoma Kageuchi",
		id = 1,
		model = ReplicatedStorage.items.weapons["Amenoma Kageuchi"],
		class = "single_wield",
		rarity = 4,
		zone = 1,
		iconId = "rbxassetid://12182177435",

		power = 1745,
		coin = 24300,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 24,
		basicAttackCooldown = 0.05,
	},
	["Aquila Favonia"] = {
		name = "Aquila Favonia",
		id = 2,
		model = ReplicatedStorage.items.weapons["Aquila Favonia"],
		class = "single_wield",
		rarity = 3,
		zone = 2,
		iconId = "rbxassetid://12182192788",

		power = 10463,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 26,
		basicAttackCooldown = 0.05,
	},
	["Bakufu"] = {
		name = "Bakufu",
		id = 3,
		model = ReplicatedStorage.items.weapons["Bakufu"],
		class = "single_wield",
		rarity = 4,
		zone = 5,
		iconId = "rbxassetid://12192115685",

		power = 975000000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 60,
		basicAttackCooldown = 0.05,
	},
	["Blackcliff Longsword"] = {
		name = "Blackcliff Longsword",
		id = 4,
		model = ReplicatedStorage.items.weapons["Blackcliff Longsword"],
		class = "single_wield",
		rarity = 5,
		iconId = "rbxassetid://12192183094",

		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 15,
		basicAttackCooldown = 0.05,
	},
	["Boreas"] = {
		name = "Boreas",
		id = 5,
		model = ReplicatedStorage.items.weapons["Boreas"],
		class = "single_wield",
		rarity = 3,
		zone = 4,
		iconId = "rbxassetid://12192107100",

		power = 1440000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 44,
		basicAttackCooldown = 0.05,
	},
	["Cool Steel"] = {
		name = "Cool Steel",
		id = 6,
		model = ReplicatedStorage.items.weapons["Cool Steel"],
		class = "single_wield",
		rarity = 1,
		zone = 3,
		iconId = "rbxassetid://12191718361",

		power = 24800,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 23,
		basicAttackCooldown = 0.05,
	},
	["Dark Iron Sword"] = {
		name = "Dark Iron Sword",
		id = 7,
		model = ReplicatedStorage.items.weapons["Dark Iron Sword"],
		class = "single_wield",
		rarity = 3,
		zone = 1,
		iconId = "rbxassetid://12310931241",

		power = 439,
		coin = 8100,
		baseDamage = 100,
		critChance = 0.4,
		critMultiplication = { 1.2, 1.5 },
		knockback = 17,
		basicAttackCooldown = 0.05,
	},
	["Dull Blade"] = {
		name = "Dull Blade",
		id = 8,
		model = ReplicatedStorage.items.weapons["Dull Blade"],
		class = "single_wield",
		rarity = 1,
		zone = 1,
		iconId = "rbxassetid://12191690446",

		power = 63,
		coin = 90,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 7,
		basicAttackCooldown = 0.05,
	},
	["Festering Desire"] = {
		name = "Festering Desire",
		id = 9,
		model = ReplicatedStorage.items.weapons["Festering Desire"],
		class = "single_wield",
		rarity = 1,
		zone = 3,
		iconId = "rbxassetid://12191718588",

		power = 45000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 25,
		basicAttackCooldown = 0.05,
	},
	["Filet Blade"] = {
		name = "Filet Blade",
		id = 10,
		model = ReplicatedStorage.items.weapons["Filet Blade"],
		class = "single_wield",
		rarity = 1,
		zone = 2,
		iconId = "rbxassetid://12182177164",

		power = 2081,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 16,
		basicAttackCooldown = 0.05,
	},
	["Freedom Sworn"] = {
		name = "Freedom Sworn",
		id = 11,
		model = ReplicatedStorage.items.weapons["Freedom Sworn"],
		class = "single_wield",
		rarity = 4,
		zone = 4,
		iconId = "rbxassetid://12192106910",

		power = 8800000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 51,
		basicAttackCooldown = 0.05,
	},
	["Harbinger Of Dawn"] = {
		name = "Harbinger Of Dawn",
		id = 12,
		model = ReplicatedStorage.items.weapons["Harbinger Of Dawn"],
		class = "single_wield",
		rarity = 1,
		zone = 2,
		iconId = "rbxassetid://12182193155",

		power = 1648,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 14,
		basicAttackCooldown = 0.05,
	},
	["Iron Sting"] = {
		name = "Iron Sting",
		id = 13,
		model = ReplicatedStorage.items.weapons["Iron Sting"],
		class = "single_wield",
		rarity = 2,
		zone = 2,
		iconId = "rbxassetid://12182192991",

		power = 4052,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 21,
		basicAttackCooldown = 0.05,
	},
	["Katana"] = {
		name = "Katana",
		id = 14,
		model = ReplicatedStorage.items.weapons["Katana"],
		class = "single_wield",
		rarity = 2,
		zone = 3,
		iconId = "rbxassetid://12191718937",

		power = 92000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 30,
		basicAttackCooldown = 0.05,
	},
	["Lions Roar"] = {
		name = "Lions Roar",
		id = 15,
		model = ReplicatedStorage.items.weapons["Lions Roar"],
		class = "single_wield",
		rarity = 2,
		zone = 5,
		iconId = "rbxassetid://12192114635",

		power = 72500000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 48,
		basicAttackCooldown = 0.05,
	},
	["Mistsplitter Reforged"] = {
		name = "Mistsplitter Reforged",
		id = 16,
		model = ReplicatedStorage.items.weapons["Mistsplitter Reforged"],
		class = "single_wield",
		rarity = 3,
		zone = 3,
		iconId = "rbxassetid://12191719599",

		power = 135400,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 35,
		basicAttackCooldown = 0.05,
	},
	["Narukami"] = {
		name = "Narukami",
		id = 17,
		model = ReplicatedStorage.items.weapons["Narukami"],
		class = "single_wield",
		rarity = 4,
		zone = 3,
		iconId = "rbxassetid://12191719232",

		power = 230000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 42,
		basicAttackCooldown = 0.05,
	},
	["Norse"] = {
		name = "Norse",
		id = 18,
		model = ReplicatedStorage.items.weapons["Norse"],
		class = "single_wield",
		rarity = 2,
		zone = 1,
		iconId = "rbxassetid://12182177684",

		power = 180,
		coin = 900,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 12,
		basicAttackCooldown = 0.05,
	},
	["Royal Filet Blade"] = {
		name = "Royal Filet Blade",
		id = 19,
		model = ReplicatedStorage.items.weapons["Royal Filet Blade"],
		class = "single_wield",
		rarity = 3,
		zone = 5,
		iconId = "rbxassetid://12192114864",

		power = 245000000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 53,
		basicAttackCooldown = 0.05,
	},
	["Royal Longsword"] = {
		name = "Royal Longsword",
		id = 20,
		model = ReplicatedStorage.items.weapons["Royal Longsword"],
		class = "single_wield",
		rarity = 1,
		zone = 4,
		iconId = "rbxassetid://12192107865",

		power = 300000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 34,
		basicAttackCooldown = 0.05,
	},
	["Skyward Blade"] = {
		name = "Skyward Blade",
		id = 21,
		model = ReplicatedStorage.items.weapons["Skyward Blade"],
		class = "single_wield",
		rarity = 2,
		zone = 4,
		iconId = "rbxassetid://12192107567",

		power = 540000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 39,
		basicAttackCooldown = 0.05,
	},
	["Summit Shaper"] = {
		name = "Summit Shaper",
		id = 22,
		model = ReplicatedStorage.items.weapons["Summit Shaper"],
		class = "single_wield",
		rarity = 4,
		zone = 2,
		iconId = "rbxassetid://12182192661",

		power = 27615,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 33,
		basicAttackCooldown = 0.05,
	},
	["Sword Of Descension"] = {
		name = "Sword Of Descension",
		id = 23,
		model = ReplicatedStorage.items.weapons["Sword Of Descension"],
		class = "single_wield",
		rarity = 1,
		zone = 4,
		iconId = "rbxassetid://12192107276",

		power = 220000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 32,
		basicAttackCooldown = 0.05,
	},
	["The Black Sword"] = {
		name = "The Black Sword",
		id = 24,
		model = ReplicatedStorage.items.weapons["The Black Sword"],
		class = "single_wield",
		rarity = 1,
		zone = 5,
		iconId = "rbxassetid://12192115315",

		power = 14300000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 43,
		basicAttackCooldown = 0.05,
	},
	["Transcend"] = {
		name = "Transcend",
		id = 25,
		model = ReplicatedStorage.items.weapons["Transcend"],
		class = "single_wield",
		rarity = 5,
		iconId = "rbxassetid://12192182840",

		soulbound = true,

		power = 120000,
		coin = 50000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication ={ 1.2, 1.5 },
		knockback = 80,
		basicAttackCooldown = 0.05,
	},
	["Traveler's Handy Sword"] = {
		name = "Traveler's Handy Sword",
		id = 26,
		model = ReplicatedStorage.items.weapons["Traveler's Handy Sword"],
		class = "single_wield",
		rarity = 1,
		zone = 5,
		iconId = "rbxassetid://12192115109",

		power = 8000000,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 41,
		basicAttackCooldown = 0.05,
	},
	["Wooden"] = {
		name = "Wooden",
		id = 27,
		model = ReplicatedStorage.items.weapons["Wooden"],
		class = "single_wield",
		rarity = 1,
		zone = 1,
		iconId = "rbxassetid://12182177875",

		power = 27,
		coin = 10,
		baseDamage = 100,
		critChance = 0.2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 5,
		basicAttackCooldown = 0.05,
	},
	["Ark"] = {
		name = "Ark",
		id = 28,
		model = ReplicatedStorage.items.weapons["Ark"],
		class = "single_wield",
		rarity = 3,
		zone = 1,
		iconId = "rbxassetid://13351200895",

		soulbound = true,

		power = 350,
		coin = 10,
		baseDamage = 100,
		critChance = .2,
		critMultiplication = { 1.2, 1.5 },
		knockback = 13,
		basicAttackCooldown = 0.05,
	},
}
