[package]
name = "ffrostflame/bridgenet"
version = "2.0.0-rc4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A feature-packed networking library oriented towards optimization and ease of usage."
license = "MIT"